import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Saish",
      email: "saish.gadekar.58@gmail.com",
      password: bcrypt.hashSync("35059076", 8),
      isAdmin: true,
    },
    {
      name: "john",
      email: "user@gmail.com",
      password: bcrypt.hashSync("35059076", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike sports shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 500,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas fit shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Lacoste Tee shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike slim pants",
      category: "pants",
      image: "/images/p4.jpg",
      price: 350,
      countInStock: 15,
      brand: "Nike",
      rating: 3.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma slim pants",
      category: "pants",
      image: "/images/p5.jpg",
      price: 100,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas fit pants",
      category: "pants",
      image: "/images/p6.jpg",
      price: 400,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 12,
      description: "high quality product",
    },
  ],
};

export default data;
